title: Ashutosh's Personal Website
author: @ashutosh210798
email: ashutoshmaheshwari210798@gmail.com
description: > Competitive Coder
# social links
twitter_username: your-twitter-handle
github_username:  @ashutosh210798

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
